### PR TITLE
Theme dark smilem

### PR DESCRIPTION
**Pull request by TomasRoj**
Please read the Pull Requests section of the Contributing Rules at the "contributing" link to the right before submitting an issue report.

### CODE REVIEW

**Comment by TomasRoj** [comment]
Screenshot will not appear in readme until its merged

**Comment by per1234** [comment]
Would you mind setting **File > Preferences > Editor language** to "English (English)" before taking the screenshots? I know I'm maybe being too picky, but I feel like the Czech language in your screenshots could cause some confusion with people who might think that's a function of the theme.

**Comment by TomasRoj** [comment]
You are totally right. Here is the new one.
screenshot

**Comment by per1234** [comment]
Looks great! Please commit that screenshot to this PR and I'll merge.

**Comment by TomasRoj** [comment]
Here it is.

**Comment by per1234** [comment]
Thanks so much @TomasRoj!

**Pull request merged**
