### PR TITLE
Theme dark jerware

### PR DESCRIPTION
**Pull request by TomasRoj**
New screenshot added.

### CODE REVIEW

**Comment by per1234** [comment]
There's something strange going on here. The background color of your "Blink" tab is white, which makes it impossible to read the text, but on my computer it looks like this:
Clipboard01
Did you modify the theme? The tab background color should be set by tab-sel-mid.png, which looks like this:
tab-sel-mid
as well as tab-sel-left.png and tab-sel-right.png.

Did you modify the theme?

**Comment by per1234** [comment]
I also notice another more minor problem. You can see on my screenshot above the title bar of the Arduino IDE is blue, which has a good contrast against the white background of the page. On your screenshots, the color of the title bar is white, which blends in with the white background of the page and makes it hard to tell where the text of the readme ends and where the screenshot begins:
screenshot

On my computer, the title bar is white when the IDE window is unselected, and blue when it's selected. Is this the same on your computer? If so, we need to figure out why the IDE window is unselected on your screenshots. Maybe you're using some screenshot application and that application has focus? On my computer, I just press Alt+PrintScreen, which copies the screenshot of the currently selected window to the clipboard, then I paste the copied image into an image viewer and save it as a .png.

**Comment by TomasRoj** [comment]
Nothing changed everything by defsult

**Comment by TomasRoj** [comment]
*default

**Comment by per1234** [comment]
I'm going to have to investigate this because I can see the tab color is working fine for you with the themeDark-smilem and arduino-retro themes (I can't tell with processing-theme because it's white by default). The white background for the themeDark-JerWare and wiring-theme seriously harms their functionality so if this is caused by a problem in the themes I need to find a fix.

**Comment by TomasRoj** [comment]
Okay

**Comment by per1234** [comment]
I figured out the problem with the white tab background. The problem is that you installed the themes incorrectly.

processing-theme has a white tab background and contains .svg files for the tabs. The other themes do not contain .svg files for the tabs. The Arduino IDE uses the .svg files by preference. So if you first install processing-theme and then install one of the other themes over the top of processing-theme, then the .svg files of processing-theme aren't overwritten and so the processing-theme style tab background is still used with the new theme. You need to delete all the old theme files from the theme folder before installing a new theme.

**Comment by TomasRoj** [comment]
Sorry but I have only one theme at a time. I dont have multiple themes there.

**Comment by per1234** [comment]
Try this:

1. Delete the folder where you install themes.
2. Download the themeDarkJerWare theme: https://github.com/per1234/ino-themes/archive/themeDark-Jerware.zip
3. Unzip the downloaded file.
4. Copy the `theme` folder from the unzipped file to the location where you install themes.
5. Restart the Arduino IDE if it's running.

Do you still see a white background color on the tab?

**Comment by TomasRoj** [comment]
Nevermind, I corrected somehow. It is good now. What about other pull requests is there some problem with merging them?

**Comment by per1234** [comment]
Thanks!

**Pull request merged**
